file = { soi ~ (attribute ~ "\n")* ~ "%%\n" ~ syllable* ~ "\n"* ~ eoi }

attribute = { attribute_key ~ ":" ~ attribute_value ~ ";"}
attribute_key = { (!(":"|";") ~ any)* }
attribute_value = { (!(":"|";") ~ any)* }


clef = { ("c" | "f") ~ ('1'..'4') }
note = { position ~ suffix? }
position = { ('a'..'m') }
suffix = { ("~" | ">" | "<" | "v" | "V" | "o~" | "o<" | "o" | "w" | "s<" | "s") }
syllable = { string ~ "(" ~ (clef | note+) ~ ")" }

string = { ('a'..'z' | 'A'..'Z' | " ")* }
